version: '3.9'

services:
  nginx-loadbalancer:
    # Apple M1 Chip
    platform: linux/amd64
    image: nginx:latest
    container_name: nginx-loadbalancer
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx-loadbalancer.conf:/etc/nginx/nginx.conf:ro
      - ./selfsigned.crt:/etc/ssl/certs/selfsigned.crt:ro
      - ./selfsigned.key:/etc/ssl/private/selfsigned.key:ro
    networks:
      - backend-network

  static-app1:
    # Apple M1 Chip
    platform: linux/amd64
    image: nginx:latest
    container_name: static-app1
    restart: always
    ports:
      - 8090:80
    volumes:     
      - ./app1.html:/usr/share/nginx/html/index.html:ro
    networks:
      - backend-network

  static-app2:
    # Apple M1 Chip
    platform: linux/amd64
    image: nginx:latest
    container_name: static-app2
    restart: always
    ports:
      - 8092:80
    volumes:     
      - ./app2.html:/usr/share/nginx/html/index.html:ro
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
